### ISSUE TITLE
Optional removal of self-dependence for recurring jobs

### ISSUE THREAD

**Issue by molet** [cihga39871/JobSchedulers.jl#14]
I have a recurring job whose function can sometimes take longer to finish than the actual period of recurrence. The subsequent call of function would be independent of the previous one, however due to the implicit dependence, it's not started until the previous one is finished. Would it be possible to add some option that removes this dependence?

As an MWE, this is what I have now (the effective function call period becomes 6 seconds):
```julia
julia> using JobSchedulers
julia> function f()  # function runs within 4 seconds
           sleep(4)
           println(Dates.format(now(), "HH:MM:SS"))
       end;
julia> submit!(f, cron=Cron("*/2", "*", "*", "*", "*", "*"));  # function call at every 2 second, starting at 15:19:16
15:19:20
15:19:26
15:19:32
15:19:38
...
```

What would be great to have is something like this (the function call is 2 seconds as specified by cron):
```julia
 julia> submit!(f, cron=Cron("*/2", "*", "*", "*", "*", "*"), remove_self_dependence=true);  # function call at every 2 second, starting at 15:19:16
15:19:20
15:19:22
15:19:24
15:19:26
...
```

**Comment by molet** [comment]
I mean the subsequent data wouldn't be even attempted to be obtained. Let's say that each time `my_scraping_function` is called it tries to download the data of the current time. Now if the function is called at 9:35 but there is a delay and that particular data is finally published at 9:42, then we would miss the function call (and so obtaining the data) at 9:40, and the next call will attempt to get data only at 9:45.

**Comment by cihga39871** [comment]
If I were you, I probably will obtain all data I can get through a single request, and add new data to my existing database. The time they publish does not matter, right?

**Comment by molet** [comment]
Well, actually it does: besides the actual data, the (approximate and potentially delayed) publish date would also be recorded.

**Comment by cihga39871** [comment]
So the problem solved! Have a good one!
