### ISSUE TITLE
Back-ends for JobScheduler

### ISSUE THREAD

**Issue by SamuelBrand1** [cihga39871/JobSchedulers.jl#15]
I'm looking at integrating `JobScheduler` into an analysis batch workflow for a package we're developing https://github.com/CDCgov/Rt-without-renewal/tree/main/pipeline .

Are there any examples of/is there support for using `JobScheduler` with some kind of backend, e.g. a SLURM cluster?

**Comment by seabbs** [comment]
and just to add to this if there is no support is there a model for how `JobScheduler` would interact with a distributed workflow (i.e would you distribute with a job etc.)

**Comment by cihga39871** [comment]
Thank you for your interest in JobSchedulers.

JobSchedulers is an independent queuing system, so it does not directly interact with SLURM or PBS. JobSchedulers is designed to pack a whole pipeline into one program using multiple CPU in a single node. The pipeline is then submitted as a single job to SLURM.

A mini example (screenshot at 16:18 from the JobSchedulers presentation at JuliaCon https://www.youtube.com/watch?v=ECERq8BHvn4) :
![image](https://github.com/cihga39871/JobSchedulers.jl/assets/20528240/8cb25420-11a9-405c-80fb-0d2bcc807230)

The JobSchedulers and Pipelines ecosystem is extensively used in projects. For example, an online DNA classification service (www.clasnip.com) uses the ecosystem for job queuing and resource management. Hundreds to thousands of jobs might be created when calling the database building module in Clasnip.

Currently, it does not support spawn tasks between nodes.

**Comment by seabbs** [comment]
Thanks a lot for this! I think sadly this means it will be hard to use in our project but no big deal there. 

Potentially our lack of understanding suggests an update to the docs to clarify the use case?

**Comment by cihga39871** [comment]
Thanks for the suggestion. I will add a back-end page in manual.

A short version of backend: JobSchedulers uses Julia's internal Threads module, and has its own way to spawn tasks to threads. A task is 'sticky' to a specific thread, and no other jobs use the same thread. It prevents threads migration and competition. You can think it is like a 'distributed system', but all variables are shared.
